/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author Gerferson
 */
public class telaInicial extends javax.swing.JFrame  implements ActionListener, ItemListener{

    /**
     * Creates new form telaInicial
     */
    private ImageIcon vetletras[] = new ImageIcon [26];
    private JButton vetbotao[] = new JButton [26];
    private JPanel painelLetras = new JPanel();
    
    //RouletteWheel roleta = new RouletteWheel();
    String seta="com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    
    public telaInicial() {
        initComponents();
        lookandfell();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nome_jogo = new javax.swing.JLabel();
        jPanelRodar = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton_Avancar = new javax.swing.JButton();
        jButton_Voltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabelteste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_nome_jogo.setText("                    JOGO DOS ACENTOS");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/til.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/agudo_1.png"))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/i.png"))); // NOI18N

        jButton5.setText("Sortear");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/mm.png"))); // NOI18N

        jButton_Avancar.setText("PROXIMA");
        jButton_Avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AvancarActionPerformed(evt);
            }
        });

        jButton_Voltar.setText("ANTERIOR");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        jButton1.setText("Rodar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRodarLayout = new javax.swing.GroupLayout(jPanelRodar);
        jPanelRodar.setLayout(jPanelRodarLayout);
        jPanelRodarLayout.setHorizontalGroup(
            jPanelRodarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodarLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanelRodarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRodarLayout.createSequentialGroup()
                        .addComponent(jButton_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Avancar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRodarLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanelRodarLayout.setVerticalGroup(
            jPanelRodarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelRodarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addGroup(jPanelRodarLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton5)))
                .addGap(33, 33, 33)
                .addGroup(jPanelRodarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Voltar)
                    .addComponent(jButton_Avancar)
                    .addComponent(jButton1))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jButton7.setText("G");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("E");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("R");

        jButton10.setText("F");

        jButton11.setText("E");

        jButton12.setText("R");
        jButton12.setFocusTraversalPolicyProvider(true);
        jButton12.setPreferredSize(new java.awt.Dimension(7, 15));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("S");

        jButton14.setText("O");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("N");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelteste, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelteste, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel_nome_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelRodar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_nome_jogo)
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRodar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AvancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AvancarActionPerformed

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        fazPainelBotoes ();
        habilitaBotoes ();
        this.update(getGraphics());
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //jPanelRodar.add(roleta);
        //dispose();
        
        
                //gui.setDefaultCloseOperation(GUI.EXIT_ON_CLOSE);
        JPanel n = new JPanel();
        n.setSize(100,100);
        n.setForeground(Color.red);
                jPanelRodar.add(n);
                this.update(getGraphics());
                dispose();
                GUI gui=new GUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jLabelteste.setText("^");
        this.update(getGraphics());
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
                
            }
        });
    }
    
    public void lookandfell() {
    try{
        UIManager.setLookAndFeel(seta);
        SwingUtilities.updateComponentTreeUI(this);
        
    }catch(Exception erro){
        JOptionPane.showMessageDialog(null,"erro em alterar o tema"+erro);
    }
}

    
    private void fazPainelBotoes () {
		this.painelLetras = new JPanel ();
		this.painelLetras.setSize (1000,200);
		this.painelLetras.setLocation(0,500);
		//this.painelLetras.setBackground(new Color (100,50,230));//teste
		this.painelLetras.setLayout (null);
		getContentPane().add(this.painelLetras);
		char letter = 'a';	
		for (byte i = 0; i < 26; i++) {
			letter = (char)(i + 'a');
			this.vetletras[i] = new ImageIcon ("img\\"+letter+".gif");
			this.vetbotao[i] = new JButton (vetletras[i]);
			//this.vetbotao[i].setBackground(Color.WHITE); //teste
			this.vetbotao[i].setFocusable(false);
			this.vetbotao[i].setRolloverEnabled(false);
			this.vetbotao[i].setSize(60,52);
			this.vetbotao[i].addActionListener(this);
			switch (i) {
			case 0: this.vetbotao[0].setLocation (45,10);
					break;
			case 1: this.vetbotao[1].setLocation (115,10);
					break;
			case 2: this.vetbotao[2].setLocation (185,10);
					break;
			case 3: this.vetbotao[3].setLocation (255,10);
					break;
			case 4: this.vetbotao[4].setLocation (325,10);
					break;
			case 5: this.vetbotao[5].setLocation (395,10);
					break;
			case 6: this.vetbotao[6].setLocation (465,10);
					break;
			case 7: this.vetbotao[7].setLocation (535,10);
					break;
			case 8: this.vetbotao[8].setLocation (605,10);
					break;
			case 9: this.vetbotao[9].setLocation (675,10);
					break;
			case 10: this.vetbotao[10].setLocation (745,10);
					break;
			case 11: this.vetbotao[11].setLocation (815,10);
					break;
			case 12: this.vetbotao[12].setLocation (885,10);
					break; 
			case 13: this.vetbotao[13].setLocation (45,70);
					break;
			case 14: this.vetbotao[14].setLocation (115,70);
					break;
			case 15: this.vetbotao[15].setLocation (185,70);
					break;
			case 16: this.vetbotao[16].setLocation (255,70);
					break;
			case 17: this.vetbotao[17].setLocation (325,70);
					break;
			case 18: this.vetbotao[18].setLocation (395,70);
					break;
			case 19: this.vetbotao[19].setLocation (465,70);
					break;
			case 20: this.vetbotao[20].setLocation (535,70);
					break;
			case 21: this.vetbotao[21].setLocation (605,70);
					break;
			case 22: this.vetbotao[22].setLocation (675,70);
					break;
			case 23: this.vetbotao[23].setLocation (745,70);
					break;
			case 24: this.vetbotao[24].setLocation (815,70);
					break;
			case 25: this.vetbotao[25].setLocation (885,70);	
					break;
			}			
			this.painelLetras.add(this.vetbotao[i]);
		}			
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_Avancar;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel_nome_jogo;
    private javax.swing.JLabel jLabelteste;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelRodar;
    // End of variables declaration//GEN-END:variables
private void habilitaBotoes () {
		for (int i = 0; i < 26; i++) {
			this.vetbotao[i].setEnabled(true);
		}
	}
    @Override
    public void actionPerformed(ActionEvent e) {
        eventoMenu (e);
        eventoBotaoLetras (e);//To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void eventoMenu (ActionEvent e) {
		
		
		
		
	}
	
	//m�todo que trata os eventos dos bot�es das letras
	public void eventoBotaoLetras (ActionEvent e) {
		int quantErro;
		char letra;
		String secret;
		for (int i = 0; i < 26; i++) {
			if (e.getSource() == this.vetbotao[i]){
				this.vetbotao[i].setEnabled(false);
				letra = (char) ('A' + i);
				//quantErro = this.jogo.getErros();
				//this.jogo.acertou(letra);
				
				
				
				break;
			}
		}
	}
}
