/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import controle.GerenciadorCursosSingleton;

/**
 *
 * @author Aislan
 */
public class TelaProfessor extends javax.swing.JFrame {
    private String nomeProfessor;
    /**
     * Creates new form TelaProfessor
     */
    public TelaProfessor() {
        initComponents();
    }
    public TelaProfessor(String nomeProfessor) {
        this.nomeProfessor = nomeProfessor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMensagens = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_turmas = new javax.swing.JList();
        jBT_curso = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jM_sair = new javax.swing.JMenu();
        jMCronograma = new javax.swing.JMenu();
        jMDiario = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1151, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("TURMAS");

        jL_turmas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jL_turmas.setToolTipText("Selecione uma disciplina");
        jScrollPane1.setViewportView(jL_turmas);

        jBT_curso.setBackground(new java.awt.Color(0, 153, 153));
        jBT_curso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBT_curso.setForeground(new java.awt.Color(255, 255, 255));
        jBT_curso.setText("Avançar");
        jBT_curso.setToolTipText("");
        jBT_curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBT_cursoMouseClicked(evt);
            }
        });
        jBT_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_cursoActionPerformed(evt);
            }
        });

        jM_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/back.png"))); // NOI18N
        jM_sair.setToolTipText("Voltar");
        jM_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_sairMouseClicked(evt);
            }
        });
        jMenuBar2.add(jM_sair);

        jMCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/calendario.png"))); // NOI18N
        jMCronograma.setToolTipText("Cronograma");
        jMCronograma.setEnabled(false);
        jMenuBar2.add(jMCronograma);

        jMDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/presença.png"))); // NOI18N
        jMDiario.setToolTipText("Diário");
        jMDiario.setEnabled(false);
        jMenuBar2.add(jMDiario);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(497, 497, 497)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBT_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jBT_curso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBT_cursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_cursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT_cursoMouseClicked

    private void jBT_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_cursoActionPerformed
        TelaTurma tdisciplina = new TelaTurma();
        tdisciplina.setExtendedState(MAXIMIZED_BOTH);
        tdisciplina.setVisible(true);
    }//GEN-LAST:event_jBT_cursoActionPerformed

    private void jM_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_sairMouseClicked
        dispose();
    }//GEN-LAST:event_jM_sairMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        for(int i = 0; i < GerenciadorCursosSingleton.getInstance().getListadecursos().size();i++){
            if(GerenciadorCursosSingleton.getInstance().getListadecursos().get(i).getListaDisciplinas().get(i).getListaTurmas().get(i).getProfessor().getMatricula().equals(nomeProfessor)){
                jMensagens.setText("Seja bem-vindo docente, " + GerenciadorCursosSingleton.getInstance().getListadecursos().get(i).getListaDisciplinas().get(i).getListaTurmas().get(i).getProfessor().getNomeUsuario());
                jL_turmas.setListData(GerenciadorCursosSingleton.getInstance().getListadecursos().get(i).getListaDisciplinas().get(i).getListaTurmas().toArray());
            }
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_curso;
    private javax.swing.JList jL_turmas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMCronograma;
    private javax.swing.JMenu jMDiario;
    private javax.swing.JMenu jM_sair;
    private javax.swing.JLabel jMensagens;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
