/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import controle.GerenciadorCursosSingleton;

/**
 *
 * @author Aislan
 */
public class TelaTurma extends javax.swing.JFrame {

    /**
     * Creates new form TelaDisciplina
     */
    public TelaTurma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBT_cronograma = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBT_diarioRelatorio = new javax.swing.JButton();
        jBT_diario = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jM_sair = new javax.swing.JMenu();
        jMCronograma = new javax.swing.JMenu();
        jMDiario = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disciplina");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CCF313 - Programação Orientada a Objetos - Turma 1");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calendário Acadêmico"));

        jBT_cronograma.setBackground(new java.awt.Color(0, 153, 153));
        jBT_cronograma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBT_cronograma.setForeground(new java.awt.Color(255, 255, 255));
        jBT_cronograma.setText("Lançar conteúdo");
        jBT_cronograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_cronogramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBT_cronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jBT_cronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Diário"));

        jBT_diarioRelatorio.setBackground(new java.awt.Color(0, 153, 153));
        jBT_diarioRelatorio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBT_diarioRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        jBT_diarioRelatorio.setText("Obter relatório");
        jBT_diarioRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_diarioRelatorioActionPerformed(evt);
            }
        });

        jBT_diario.setBackground(new java.awt.Color(0, 153, 153));
        jBT_diario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBT_diario.setForeground(new java.awt.Color(255, 255, 255));
        jBT_diario.setText("Lançar faltas");
        jBT_diario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_diarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBT_diario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jBT_diarioRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBT_diarioRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBT_diario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jM_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/back.png"))); // NOI18N
        jM_sair.setToolTipText("Voltar");
        jM_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_sairMouseClicked(evt);
            }
        });
        jM_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_sairActionPerformed(evt);
            }
        });
        jMenuBar2.add(jM_sair);

        jMCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/calendario.png"))); // NOI18N
        jMCronograma.setToolTipText("Cronograma");
        jMCronograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMCronogramaMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMCronograma);

        jMDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fronteira/presença.png"))); // NOI18N
        jMDiario.setToolTipText("Diário");
        jMDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMDiarioMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMDiario);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_sairMouseClicked
        dispose();
    }//GEN-LAST:event_jM_sairMouseClicked

    private void jBT_cronogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_cronogramaActionPerformed
        //for(int i = 0; i < GerenciadorCursosSingleton.getInstance().getListadecursos().size();i++){
            //if(GerenciadorCursosSingleton.getInstance().getListadecursos().get(i).getListaDisciplinas().get(i).getListaTurmas().get(i).inserirCronogramaNaTurma()){
                TelaCronograma tc = new TelaCronograma();
                tc.setExtendedState(MAXIMIZED_BOTH);
                tc.setVisible(true);
            //}
        //}
        
        
    }//GEN-LAST:event_jBT_cronogramaActionPerformed

    private void jBT_diarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_diarioActionPerformed
        TelaChamada frame = new TelaChamada();  
       // frame.setDefaultCloseOperation( EXIT_ON_CLOSE );  
        frame.pack();  
        frame.setVisible(true);
    }//GEN-LAST:event_jBT_diarioActionPerformed

    private void jMDiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMDiarioMouseClicked
        TelaChamada tc = new TelaChamada();
        tc.setExtendedState(MAXIMIZED_BOTH);
        tc.setVisible(true);
    }//GEN-LAST:event_jMDiarioMouseClicked

    private void jMCronogramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCronogramaMouseClicked
        TelaCronograma tc = new TelaCronograma();
        tc.setExtendedState(MAXIMIZED_BOTH);
        tc.setVisible(true);
    }//GEN-LAST:event_jMCronogramaMouseClicked

    private void jBT_diarioRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_diarioRelatorioActionPerformed
        ///TelaRelatorioDeFaltasOutra telaDiario = new TelaRelatorioDeFaltasOutra();
        //telaDiario.criaJanela();
        new TelaRelatorioDeFaltas();
    }//GEN-LAST:event_jBT_diarioRelatorioActionPerformed

    private void jM_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTurma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_cronograma;
    private javax.swing.JButton jBT_diario;
    private javax.swing.JButton jBT_diarioRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMCronograma;
    private javax.swing.JMenu jMDiario;
    private javax.swing.JMenu jM_sair;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
