/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fronteira;

import Entidade.Arduino;
import Entidade.SerialRxTx;
import TerGrafico.Alarm;
import TerGrafico.ThermometerDemo1;
import TerGrafico.TimerPanel;
import controle.GerenciadorSingleton;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.TextField;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Gerferson
 */
public class TelaPrincipal extends javax.swing.JFrame {
    public ThermometerDemo1 panel = new ThermometerDemo1();
    int cont1=0,cont2=0,cont3=0,cont4=0,font=0,at=0;
    //Arduino conn = new Arduino();
    //SerialRxTx serial= new SerialRxTx();
    
    GerenciadorSingleton instance=new GerenciadorSingleton();
    Alarm n = new Alarm();
    
    String seta="com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    public TelaPrincipal() {
        initComponents();
       instance.iniciarSistema();
        lookandfell();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        controle = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jBLedOn = new javax.swing.JButton();
        jBLedOff = new javax.swing.JButton();
        jBClose3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonLigarDesligaAmbiente3 = new javax.swing.JButton();
        jButtonLigarDesligaAmbiente1 = new javax.swing.JButton();
        jButtonLigarDesligaAmbiente2 = new javax.swing.JButton();
        jButtonLigarDesligaAmbiente4 = new javax.swing.JButton();
        jPanelLigacao = new javax.swing.JPanel();
        try {
            jP =(javax.swing.JPanel)java.beans.Beans.instantiate(getClass().getClassLoader(), "Fronteira.TelaPrincipal_jP");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jButton1 = new javax.swing.JButton();
        jButtonEnviarTemperatura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonFont = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTF_matricula = new javax.swing.JTextField();
        jBT_login = new javax.swing.JButton();
        jPF_senha = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPF_senhaAlarme = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabelCadiado = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROLE");
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setAlignmentX(1.0F);
        jTabbedPane1.setAlignmentY(1.0F);
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(150, 160));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(100, 255, 200));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        controle.setPreferredSize(new java.awt.Dimension(650, 600));
        controle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Mexer(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 153));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 102));
        jSeparator1.setOpaque(true);

        jBLedOn.setText("Ligar");
        jBLedOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLedOnMouseClicked(evt);
            }
        });
        jBLedOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLedOnActionPerformed(evt);
            }
        });

        jBLedOff.setText("Desligar");
        jBLedOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLedOffMouseClicked(evt);
            }
        });

        jBClose3.setText("Sair");
        jBClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBClose3MouseClicked(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 153));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 102));
        jSeparator2.setOpaque(true);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 153));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 102));
        jSeparator3.setOpaque(true);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 153));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 102));
        jSeparator4.setOpaque(true);

        jButtonLigarDesligaAmbiente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/acessa.png"))); // NOI18N
        jButtonLigarDesligaAmbiente3.setBorder(null);
        jButtonLigarDesligaAmbiente3.setBorderPainted(false);
        jButtonLigarDesligaAmbiente3.setContentAreaFilled(false);
        jButtonLigarDesligaAmbiente3.setOpaque(true);
        jButtonLigarDesligaAmbiente3.setRequestFocusEnabled(false);
        jButtonLigarDesligaAmbiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLigarDesligaAmbiente3ActionPerformed(evt);
            }
        });

        jButtonLigarDesligaAmbiente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/acessa.png"))); // NOI18N
        jButtonLigarDesligaAmbiente1.setBorder(null);
        jButtonLigarDesligaAmbiente1.setBorderPainted(false);
        jButtonLigarDesligaAmbiente1.setContentAreaFilled(false);
        jButtonLigarDesligaAmbiente1.setFocusPainted(false);
        jButtonLigarDesligaAmbiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLigarDesligaAmbiente1ActionPerformed(evt);
            }
        });

        jButtonLigarDesligaAmbiente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/acessa.png"))); // NOI18N
        jButtonLigarDesligaAmbiente2.setBorder(null);
        jButtonLigarDesligaAmbiente2.setBorderPainted(false);
        jButtonLigarDesligaAmbiente2.setContentAreaFilled(false);
        jButtonLigarDesligaAmbiente2.setRequestFocusEnabled(false);
        jButtonLigarDesligaAmbiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLigarDesligaAmbiente2ActionPerformed(evt);
            }
        });

        jButtonLigarDesligaAmbiente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/acessa.png"))); // NOI18N
        jButtonLigarDesligaAmbiente4.setBorder(null);
        jButtonLigarDesligaAmbiente4.setBorderPainted(false);
        jButtonLigarDesligaAmbiente4.setContentAreaFilled(false);
        jButtonLigarDesligaAmbiente4.setRequestFocusEnabled(false);
        jButtonLigarDesligaAmbiente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLigarDesligaAmbiente4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controleLayout = new javax.swing.GroupLayout(controle);
        controle.setLayout(controleLayout);
        controleLayout.setHorizontalGroup(
            controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controleLayout.createSequentialGroup()
                .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(controleLayout.createSequentialGroup()
                        .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controleLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jBLedOn)
                                .addGap(18, 18, 18)
                                .addComponent(jBLedOff))
                            .addGroup(controleLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jBClose3)
                                .addGap(81, 81, 81)
                                .addComponent(jButtonLigarDesligaAmbiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(167, 167, 167)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controleLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButtonLigarDesligaAmbiente3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLigarDesligaAmbiente4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLigarDesligaAmbiente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
            .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controleLayout.createSequentialGroup()
                    .addContainerGap(551, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        controleLayout.setVerticalGroup(
            controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controleLayout.createSequentialGroup()
                .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(controleLayout.createSequentialGroup()
                                .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBLedOn)
                                    .addComponent(jBLedOff))
                                .addGap(37, 37, 37)
                                .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBClose3)
                                    .addComponent(jButtonLigarDesligaAmbiente1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))))
                    .addGroup(controleLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButtonLigarDesligaAmbiente2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controleLayout.createSequentialGroup()
                        .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(controleLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButtonLigarDesligaAmbiente3)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controleLayout.createSequentialGroup()
                        .addComponent(jButtonLigarDesligaAmbiente4)
                        .addGap(37, 37, 37))))
            .addGroup(controleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controleLayout.createSequentialGroup()
                    .addContainerGap(325, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(317, 317, 317)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(controle, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controle, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(673, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagesluzes2.png")), jPanel1); // NOI18N

        jPanelLigacao.setBackground(new java.awt.Color(100, 255, 200));
        jPanelLigacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLigacaoMouseClicked(evt);
            }
        });

        jButton1.setText("Obter Temperatura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonEnviarTemperatura.setText("Enviar Temperatura");
        jButtonEnviarTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarTemperaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPLayout = new javax.swing.GroupLayout(jP);
        jP.setLayout(jPLayout);
        jPLayout.setHorizontalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnviarTemperatura)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPLayout.setVerticalGroup(
            jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLayout.createSequentialGroup()
                .addContainerGap(503, Short.MAX_VALUE)
                .addGroup(jPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonEnviarTemperatura))
                .addGap(24, 24, 24))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("                       Climatização");

        javax.swing.GroupLayout jPanelLigacaoLayout = new javax.swing.GroupLayout(jPanelLigacao);
        jPanelLigacao.setLayout(jPanelLigacaoLayout);
        jPanelLigacaoLayout.setHorizontalGroup(
            jPanelLigacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLigacaoLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(621, Short.MAX_VALUE))
            .addGroup(jPanelLigacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLigacaoLayout.createSequentialGroup()
                    .addContainerGap(455, Short.MAX_VALUE)
                    .addComponent(jP, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );
        jPanelLigacaoLayout.setVerticalGroup(
            jPanelLigacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLigacaoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1312, Short.MAX_VALUE))
            .addGroup(jPanelLigacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLigacaoLayout.createSequentialGroup()
                    .addContainerGap(361, Short.MAX_VALUE)
                    .addComponent(jP, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(427, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Imagens/term.png")), jPanelLigacao, "Climatizar o ambiente auemntando ou diminuido a temepratura"); // NOI18N
        //carrega a imagem passando o nome da mesma

        jPanel4.setBackground(new java.awt.Color(100, 255, 200));

        jButton4.setText("Ligar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Desligar");

        jButtonFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fonte-imagem-animada-0024maior.gif"))); // NOI18N
        jButtonFont.setBorder(null);
        jButtonFont.setBorderPainted(false);
        jButtonFont.setContentAreaFilled(false);
        jButtonFont.setOpaque(true);
        jButtonFont.setRequestFocusEnabled(false);
        jButtonFont.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dica(evt);
            }
        });
        jButtonFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFontActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButtonFont, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(361, 361, 361))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFont, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jButtonFont.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(690, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Imagens/chafariz.png")), jPanel4); // NOI18N

        jPanel5.setBackground(new java.awt.Color(100, 255, 200));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acesso restrito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jTF_matricula.setEditable(false);
        jTF_matricula.setBackground(new java.awt.Color(204, 204, 204));
        jTF_matricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTF_matricula.setText("Usuario");
        jTF_matricula.setToolTipText("Insira seu usuario");
        jTF_matricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTF_matriculaMousePressed(evt);
            }
        });

        jBT_login.setBackground(new java.awt.Color(0, 153, 153));
        jBT_login.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBT_login.setForeground(new java.awt.Color(255, 255, 255));
        jBT_login.setText("LOGIN");
        jBT_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBT_loginMouseClicked(evt);
            }
        });
        jBT_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_loginActionPerformed(evt);
            }
        });

        jPF_senha.setEditable(false);
        jPF_senha.setBackground(new java.awt.Color(204, 204, 204));
        jPF_senha.setText("Senha");
        jPF_senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPF_senhaMouseClicked(evt);
            }
        });
        jPF_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPF_senhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_matricula, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jPF_senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jBT_login)
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTF_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPF_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBT_login, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jButton5.setText("Ativar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Desativar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPF_senhaAlarme.setEditable(false);
        jPF_senhaAlarme.setBackground(new java.awt.Color(204, 204, 204));
        jPF_senhaAlarme.setText("Senha");
        jPF_senhaAlarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPF_senhaAlarmeMouseClicked(evt);
            }
        });
        jPF_senhaAlarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPF_senhaAlarmeActionPerformed(evt);
            }
        });

        jLabel2.setText("SENHA ALARME");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jPF_senhaAlarme)
                    .addGap(58, 58, 58)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(21, 21, 21))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jPF_senhaAlarme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadiado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabelCadiado, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel6.getAccessibleContext().setAccessibleName("Acesso  restrito ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(690, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Imagens/alarme2.png")), jPanel5); // NOI18N

        jPanel9.setBackground(new java.awt.Color(100, 255, 200));

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(576, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(405, 405, 405))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jButton8)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(737, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel9);

        jMenu2.setText("Voltar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fechar");
        jMenuBar1.add(jMenu3);

        jMenu1.setText("Logout");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        
    }//GEN-LAST:event_formMouseMoved

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPF_senhaAlarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPF_senhaAlarmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPF_senhaAlarmeActionPerformed

    private void jPF_senhaAlarmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPF_senhaAlarmeMouseClicked
        jPF_senhaAlarme.setText("");
        jPF_senhaAlarme.setEditable(true);
    }//GEN-LAST:event_jPF_senhaAlarmeMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if((jPF_senhaAlarme.getText().equals(""))){
            JOptionPane.showMessageDialog(rootPane, "Preenchimento dos campos é obrigatório");
        }
        if(jPF_senhaAlarme.getText().equals("12345")){
            n.stopSound();
        }
        jLabelCadiado.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\cadiadoaberto.png"));
        //this.update(getGraphics());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if((jPF_senhaAlarme.getText().equals(""))){
            JOptionPane.showMessageDialog(rootPane, "Preenchimento dos campos é obrigatório");
        }
        if(jPF_senhaAlarme.getText().equals("12345")){

            n.configure();
            n.playSound();
        }

        jLabelCadiado.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\cadiadofechado.png"));
        //this.update(getGraphics());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPF_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPF_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPF_senhaActionPerformed

    private void jPF_senhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPF_senhaMouseClicked
        jPF_senha.setText("");
        jPF_senha.setEditable(true);
    }//GEN-LAST:event_jPF_senhaMouseClicked

    private void jBT_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_loginActionPerformed
        JPanel p =new JPanel();
        JButton b1 =new JButton("Desligar");
        JButton b2 =new JButton("Ligar");
        b1.addActionListener( new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.out.println("Desligando Alarme");
            }
        });
        b2.addActionListener( new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.out.println("Ligando Alarme");
            }
        });
        JTextField text = new JTextField("Senha    ");
        //text.setSize(450,320);
        //Point pontos=new Point(600,600);

        text.setBounds(0, 0, 0, 0);
        text.setSize(450,330);

        p.setSize(400,300);
        //seta a localização - layout é null
        p.setLocation(500,100);
        p.setBackground( Color.BLUE );
        p.add(b1);
        p.add(b2);
        p.add(text);

        //panel.setLocation((d.width - panel.getSize().width) / 2, (d.height - panel.getSize().height) / 2);
        //jPanel2.add(p);
        //this.update(getGraphics());
    }//GEN-LAST:event_jBT_loginActionPerformed

    private void jBT_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_loginMouseClicked
        if(jTF_matricula.getText().equals("") || (jPF_senha.getText().equals(""))){
            JOptionPane.showMessageDialog(rootPane, "Preenchimento dos campos é obrigatório");
        }
    }//GEN-LAST:event_jBT_loginMouseClicked

    private void jTF_matriculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTF_matriculaMousePressed

        jTF_matricula.setText("");
        jTF_matricula.setEditable(true);
    }//GEN-LAST:event_jTF_matriculaMousePressed

    private void jButtonFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFontActionPerformed
        if(font==0){
            jButtonFont.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\fonteDesligadamaior.png"));
            font=1;
        }else{
            jButtonFont.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\fonte-imagem-animada-0024maior.gif"));
            font=0;
        }
    }//GEN-LAST:event_jButtonFontActionPerformed

    private void dica(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dica
        JTextField t = new JTextField("Click na imagem para ligar ou desligar a fonte   ");
        jLabel3.setText("Click na imagem para ligar ou desligar a fonte   ");
        if(at==0){
            this.update(getGraphics());
            at=1;
        }

    }//GEN-LAST:event_dica

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanelLigacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLigacaoMouseClicked

    }//GEN-LAST:event_jPanelLigacaoMouseClicked

    private void jButtonEnviarTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarTemperaturaActionPerformed
        GerenciadorSingleton novo=new GerenciadorSingleton();

        System.out.println("Temperatura " + panel.getThermo2().getValue().doubleValue());
        novo.EnviarTemperatura(panel.getThermo2().getValue().doubleValue());
    }//GEN-LAST:event_jButtonEnviarTemperaturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //setVisible(false);
        //dispose();
        //JFrame frame = new JFrame();
        //frame.getContentPane().setLayout(new BorderLayout(5, 5));
        //frame.setDefaultCloseOperation(3);
        //frame.setTitle("Temperatura");
        //frame.getContentPane().add(panel, BorderLayout.CENTER);
        //frame.setSize(400, 400);

        // Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        //frame.setLocation((d.width - frame.getSize().width) / 2, (d.height - frame.getSize().height) / 2);
        //frame.setVisible(true);
        //jP.add(panel, BorderLayout.CENTER);
        //panel.setVisible(true);
        //panel.setBackground(Color.RED);
        //seta o tamanho do painel
        panel.setSize(700,800);
        //seta a localização - layout é null
        //panel.setLocation(150,100);
        //panel.setLocation((d.width - panel.getSize().width) / 2, (d.height - panel.getSize().height) / 2);
        jP.add(panel);
        this.update(getGraphics());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Mexer(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mexer
        UIManager.put("TabbedPane.selected",Color.BLUE);
        UIManager.put("TabbedPane.unselectedTabBackground",Color.GREEN);
    }//GEN-LAST:event_Mexer

    private void jButtonLigarDesligaAmbiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLigarDesligaAmbiente4ActionPerformed
        if(cont4==0){
            jButtonLigarDesligaAmbiente4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\apagada.png"));
            cont4=1;
        }else{
            jButtonLigarDesligaAmbiente4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\acessa.png"));
            cont4=0;
        }
    }//GEN-LAST:event_jButtonLigarDesligaAmbiente4ActionPerformed

    private void jButtonLigarDesligaAmbiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLigarDesligaAmbiente2ActionPerformed
        if(cont2==0){
            jButtonLigarDesligaAmbiente2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\apagada.png"));
            cont2=1;
            instance.enviarDados('D');
        }else{
            jButtonLigarDesligaAmbiente2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\acessa.png"));
            cont2=0;
            instance.enviarDados('L');;
        }
    }//GEN-LAST:event_jButtonLigarDesligaAmbiente2ActionPerformed

    private void jButtonLigarDesligaAmbiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLigarDesligaAmbiente1ActionPerformed

        if(cont1==0){
            jButtonLigarDesligaAmbiente1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\apagada.png"));
            cont1=1;
           instance.enviarDados('D');
        }else{
            jButtonLigarDesligaAmbiente1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\acessa.png"));
            cont1=0;
            instance.enviarDados('L');
            
        }

    }//GEN-LAST:event_jButtonLigarDesligaAmbiente1ActionPerformed

    private void jButtonLigarDesligaAmbiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLigarDesligaAmbiente3ActionPerformed
        if(cont3==0){
            jButtonLigarDesligaAmbiente3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\apagada.png"));
            cont3=1;
        }else{
            jButtonLigarDesligaAmbiente3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gerferson\\Downloads\\ComunicacaoSerial-master\\Java\\ComunicacaoSerial\\src\\Imagens\\acessa.png"));
            cont3=0;
        }
    }//GEN-LAST:event_jButtonLigarDesligaAmbiente3ActionPerformed

    private void jBClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClose3MouseClicked
        // TODO add your handling code here:
        //conn.comunicacaoArduino(jBClose3);
        System.exit(0);//fecha a aplicação
    }//GEN-LAST:event_jBClose3MouseClicked

    private void jBLedOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLedOffMouseClicked
        // TODO add your handling code here:
        //conn.comunicacaoArduino(jBLedOff);
    }//GEN-LAST:event_jBLedOffMouseClicked

    private void jBLedOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLedOnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLedOnActionPerformed

    private void jBLedOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLedOnMouseClicked
        // TODO add your handling code here:
        //conn.comunicacaoArduino(jBLedOn); //Nome do botão pressionado
    }//GEN-LAST:event_jBLedOnMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        TimerPanel nov =new TimerPanel();
        nov.setHour_mid(2);
        nov.setHour_right(1);
        nov.startTimer();
        jPanel10.add(nov);
        
       
            this.update(getGraphics());
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void b1_MausePressed(java.awt.event.MouseEvent evt){
            System.out.println("Pritn botao");
    
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controle;
    private javax.swing.JButton jBClose3;
    private javax.swing.JButton jBLedOff;
    private javax.swing.JButton jBLedOn;
    private javax.swing.JButton jBT_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonEnviarTemperatura;
    private javax.swing.JButton jButtonFont;
    private javax.swing.JButton jButtonLigarDesligaAmbiente1;
    private javax.swing.JButton jButtonLigarDesligaAmbiente2;
    private javax.swing.JButton jButtonLigarDesligaAmbiente3;
    private javax.swing.JButton jButtonLigarDesligaAmbiente4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCadiado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jP;
    private javax.swing.JPasswordField jPF_senha;
    private javax.swing.JPasswordField jPF_senhaAlarme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelLigacao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTF_matricula;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
public void lookandfell() {
    try{
        UIManager.setLookAndFeel(seta);
        SwingUtilities.updateComponentTreeUI(this);
        
    }catch(Exception erro){
        JOptionPane.showMessageDialog(null,"erro em alterar o tema"+erro);
    }
}

}
